Updated test harness for new Bin/cpu/arch directory structure.

diff --git a/Bin/regress b/Bin/regress
--- a/Bin/regress
+++ b/Bin/regress
@@ -41,7 +41,7 @@ if [ $arg = all -o $arg = nj ] ; then
 NJ compiled TILT results
 ************************************************************";
 
-    (cd ./Test ; ../Bin/runall -nf);
+    if (cd ./Test ; ../Bin/runall -nf); then :; else echo "NJ compiled TILT tests failed"; exit 1; fi ;
 fi
 
 if [ $arg = all -o $arg = tilt ] ; then  
@@ -56,5 +56,5 @@ if [ $arg = all -o $arg = tilt ] ; then
 TILT compiled TILT results
 ************************************************************" ;
 
-    (cd ./Test ; ../Bin/runall -f) ;
+    if (cd ./Test ; ../Bin/runall -f) ; then :; else echo "TILT compiled TILT tests failed"; exit 1; fi ;
 fi
diff --git a/Bin/runall b/Bin/runall
--- a/Bin/runall
+++ b/Bin/runall
@@ -13,8 +13,8 @@ echo Skipping:  `awk '/^#/ {next} $2 ~ /skip/ {print $1 " "}' $testlist`
 
 # Run the ones we expect to fail
 echo 'These tests should fail....'
-"$bindir"/runtest ${1+"$@"} -F `awk '/^#/ {next} $2 ~ /fail/ {print $1}' $testlist`
+"$bindir"/runtest ${1+"$@"} -F `awk '/^#/ {next} $2 ~ /fail/ {print $1}' $testlist` || exit 1
 
 # Run the ones we expect to succeed
 echo 'These tests should succeed....'
-"$bindir"/runtest ${1+"$@"} -S `awk '/^#/ {next} $2 ~ /pass/ {print $1}' $testlist`
+"$bindir"/runtest ${1+"$@"} -S `awk '/^#/ {next} $2 ~ /pass/ {print $1}' $testlist` || exit 1
